// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using essSync.src.Database;

#nullable disable

namespace essSync.Migrations
{
    [DbContext(typeof(SharedContext))]
    [Migration("20260204122515_AddDeviceIp")]
    partial class AddDeviceIp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("essSync.src.Database.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThisDevice")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceGuid")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("essSync.src.Database.DeviceIp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGuid");

                    b.ToTable("DeviceIps");
                });

            modelBuilder.Entity("essSync.src.Database.FolderDevice", b =>
                {
                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId", "DeviceId");

                    b.HasIndex("DeviceId");

                    b.ToTable("FolderDevices");
                });

            modelBuilder.Entity("essSync.src.Database.SharedFile", b =>
                {
                    b.Property<int>("SharedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FolderId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SharedFileId");

                    b.HasIndex("FolderId");

                    b.ToTable("SharedFiles");
                });

            modelBuilder.Entity("essSync.src.Database.SharedFolder", b =>
                {
                    b.Property<int>("SharedFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("SharedFolderId");

                    b.HasIndex("FolderGuid")
                        .IsUnique();

                    b.ToTable("SharedFolders");
                });

            modelBuilder.Entity("essSync.src.Database.DeviceIp", b =>
                {
                    b.HasOne("essSync.src.Database.Device", null)
                        .WithMany("DeviceIps")
                        .HasForeignKey("DeviceGuid")
                        .HasPrincipalKey("DeviceGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("essSync.src.Database.FolderDevice", b =>
                {
                    b.HasOne("essSync.src.Database.Device", "Device")
                        .WithMany("FolderDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("essSync.src.Database.SharedFolder", "SharedFolder")
                        .WithMany("FolderDevices")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("SharedFolder");
                });

            modelBuilder.Entity("essSync.src.Database.SharedFile", b =>
                {
                    b.HasOne("essSync.src.Database.SharedFolder", "SharedFolder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedFolder");
                });

            modelBuilder.Entity("essSync.src.Database.Device", b =>
                {
                    b.Navigation("DeviceIps");

                    b.Navigation("FolderDevices");
                });

            modelBuilder.Entity("essSync.src.Database.SharedFolder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("FolderDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
